#!/bin/bash

CONFIG="$HOME/.config/hypr/Scripts/wallpaper-switcher-main/wofi/config"
STYLE="$HOME/.config/hypr/Scripts/wallpaper-switcher-main/wofi/style.css"
COLORS="$HOME/.config/hypr/Scripts/wallpaper-switcher-main/wofi/colors"

DIR=$HOME/Pictures/aesthetic/
PICS=($(ls ${DIR}))

RANDOMPICS=${PICS[$RANDOM % ${#PICS[@]}]}

if [[ $(pidof swaybg) ]]; then
    pkill swaybg
fi

wofi_command="wofi --show dmenu \
			--prompt 'choose..'
			--conf ${CONFIG} --style ${STYLE} --color ${COLORS} \
			--width=300 --height=400 \
			--cache-file=/dev/null \
			--hide-scroll --no-actions \
			--define=matching=fuzzy"

menu() {
    printf "1.Mountain\n"
    printf "2.Street\n"
    printf "3.Home\n"
    printf "4.Sky\n"
    printf "5.Ocean\n"
    printf "6.Clouds\n"
    printf "7.Forest\n"
    printf "8.Grassland\n"
    printf "9.Japan\n"
    printf "10.Whale\n"
    printf "11.Canel\n"
    printf "12.Coast\n"
	printf "13.House on the hill\n"
	printf "14.Haunted\n"
	printf "15.Ocean2\n"
	printf "16.Reze\n"
}

swww query || swww-daemon

main() {
    choice=$(menu | ${wofi_command} | cut -d. -f1)
    case $choice in
    1)
        swww img ${dir}/mybackground.jpg --transition-fps 60 --transition-type fade --transition-duration 5
        return
        ;;
    2)
        swww img ${DIR}/Anime-Japan-Street.png --transition-fps 60 --transition-type fade --transition-duration 5
        return
        ;;
    3)
        swww img ${DIR}/Dreamy-Aesthetic-Home-Under-Moonlight.png --transition-fps 60 --transition-type fade --transition-duration 5
        return
        ;;
    4)
        swww img ${DIR}/sky.jpg --transition-fps 60 --transition-type fade --transition-duration 5
        return
        ;;
    5)
        swww img ${DIR}/ocean.jpg --transition-fps 60 --transition-type fade --transition-duration 5
        return
        ;;
    6)
        swww img ${DIR}/idk.jpg --transition-fps 60 --transition-type fade --transition-duration 5
        return
        ;;
    7)
        swww img ${DIR}/Forest.png --transition-fps 60 --transition-type fade --transition-duration 5
        return
        ;;
    8)
        swww img ${DIR}/grassland.png --transition-fps 60 --transition-type fade --transition-duration 5
        return
        ;;
    9)
        swww img ${DIR}/winter_japan.png --transition-fps 60 --transition-type fade --transition-duration 5
        return
        ;;
    10)
        swww img ${DIR}/whale.png --transition-fps 60 --transition-type fade --transition-duration 5
        return
        ;;
    11)
        swww img ${DIR}/canel.png --transition-fps 60 --transition-type fade --transition-duration 5
        return
        ;;
    12)
        swww img ${DIR}/Coast.png --transition-fps 60 --transition-type fade --transition-duration 5
        return
        ;;
	13)
		swww img ${DIR}/idk.png --transition-fps 60 --transition-type fade --transition-duration 5
		return
		;;
	14)
		swww img ${DIR}/Haunted.png --transition-fps 60 --transition-type fade --transition-duration 5
		return
		;;
	15)
		swww img ${DIR}/ocean.png --transition-fps 60 --transition-type fade --transition-duration 5
		return
		;;	
	16)
		swww img ${DIR}/reze.png --transition-fps 60 --transition-type fade --transition-duration 5
		return
		;;
    esac
}

killall -f || main
